name = "laoe-infinite-buy"
compatibility_date = "2026-04-24"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "laoe-infinite-buy-db"
database_id = "placeholder"

[assets]
directory = "./"
